"""Verified, bounded bathymetry bundles with an immutable geographic dependency."""

import io
import json
import os
from collections.abc import Callable, Mapping
from dataclasses import replace
from hashlib import sha256
from pathlib import Path

import numpy as np
from PIL import Image

from dmtools.terrain.adapters.build import canonical_json, file_sha256
from dmtools.terrain.adapters.numeric import read_numeric_archive
from dmtools.terrain.adapters.world_bathymetry_inputs import (
    MAX_BATHYMETRY_INPUT_BYTES,
    inputs_document,
    inputs_from_bytes,
)
from dmtools.terrain.adapters.world_bathymetry_render import BATHYMETRY_LAYERS, bathymetry_image
from dmtools.terrain.adapters.world_context import write_world_context
from dmtools.terrain.adapters.world_context_load import read_world_context
from dmtools.terrain.adapters.world_geology import world_fingerprint
from dmtools.terrain.domain.world_bathymetry import BATHYMETRY_ALGORITHM
from dmtools.terrain.pipeline.world_bathymetry import (
    WorldBathymetry,
    bathymetry_values,
    sample_water_centres,
)

BATHYMETRY_SCHEMA = "dmtools.world-bathymetry"
BATHYMETRY_VERSION = 1
MAX_BATHYMETRY_MANIFEST_BYTES = 4 * 1024 * 1024
BATHYMETRY_PREVIEWS = ("bed.png", "distance-error.png", "support.png")
BATHYMETRY_OUTPUTS = (
    "inputs.dmbathy.json",
    "bathymetry.npz",
    "geography/context.json",
    *BATHYMETRY_PREVIEWS,
)


def bathymetry_document(
    result: WorldBathymetry,
    runtime: dict[str, object],
    outputs: Mapping[str, object],
) -> dict[str, object]:
    valid = np.isfinite(result.bed_elevation_m)
    document: dict[str, object] = {
        "schema": BATHYMETRY_SCHEMA,
        "version": BATHYMETRY_VERSION,
        "algorithm": BATHYMETRY_ALGORITHM,
        "runtime": runtime,
        "input_sha256": sha256(canonical_json(inputs_document(result.inputs))).hexdigest(),
        "geography": "geography/context.json",
        "measurement": "cell-centre-bed-elevation-metres; selected-oceans-only",
        "coast_datum_m": 0.0,
        "nodata": "nan-on-land-and-unselected-water",
        "distance_policy": "max(0,shore-sample-distance-minus-error-bound)",
        "error_scope": "shore-sampling-and-float32-only; not-geological-uncertainty",
        "sampled_cells": result.sampled_cells,
        "unsampled_ocean_ids": list(result.unsampled_ocean_ids),
        "selected_water_area_km2": sum(
            b.area_km2 for b in result.context.water_bodies if b.id in result.inputs.ocean_ids
        ),
        "deepest_sample_m": float(-np.min(result.bed_elevation_m[valid]))
        if np.any(valid)
        else None,
        "max_distance_depth_error_m": float(np.max(result.distance_depth_error_m[valid]))
        if np.any(valid)
        else None,
        "outputs": outputs,
    }
    document["bathymetry_sha256"] = sha256(canonical_json(document)).hexdigest()
    return document


def write_world_bathymetry(
    result: WorldBathymetry,
    runtime: dict[str, object],
    destination: Path,
    *,
    verify: Callable[[], None],
) -> Path:
    verify()
    target = destination.absolute()
    if target.exists() or target.is_symlink():
        raise FileExistsError(f"Bathymetry destination already exists: {target}")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.mkdir()
    data = canonical_json(inputs_document(result.inputs))
    if len(data) > MAX_BATHYMETRY_INPUT_BYTES:
        raise ValueError("Bathymetry input snapshot exceeds 40 MiB.")
    (target / "inputs.dmbathy.json").write_bytes(data)
    # Re-encode only a geography generated by this same producer, enforced by the application.
    write_world_context(result.context, runtime, target / "geography", verify=verify)
    verify()
    np.savez_compressed(
        target / "bathymetry.npz",
        allow_pickle=False,
        centre_water_body=result.centre_water_body.astype("<i4", copy=False),
        bed_elevation_m=result.bed_elevation_m.astype("<f4", copy=False),
        distance_depth_error_m=result.distance_depth_error_m.astype("<f4", copy=False),
    )
    for layer, name in zip(BATHYMETRY_LAYERS, BATHYMETRY_PREVIEWS, strict=True):
        verify()
        with bathymetry_image(result, layer) as preview:
            preview.save(target / name)
    outputs = {
        name: {"sha256": file_sha256(target / name), "bytes": (target / name).stat().st_size}
        for name in BATHYMETRY_OUTPUTS
    }
    data = canonical_json(bathymetry_document(result, runtime, outputs))
    if len(data) > MAX_BATHYMETRY_MANIFEST_BYTES:
        raise ValueError("Bathymetry manifest exceeds 4 MiB.")
    verify()
    pending = target / "manifest.pending"
    with pending.open("xb") as stream:
        stream.write(data)
        stream.flush()
        os.fsync(stream.fileno())
    verify()
    complete = target / "bathymetry.json"
    pending.replace(complete)
    return complete


def _read(path: Path, maximum: int) -> bytes:
    if path.is_symlink() or not path.is_file():
        raise ValueError(f"Bathymetry file missing or linked: {path.name}")
    with path.open("rb") as stream:
        data = stream.read(maximum + 1)
    if not 0 < len(data) <= maximum:
        raise ValueError(f"Bathymetry file empty or oversized: {path.name}")
    return data


def _unique(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"Duplicate bathymetry manifest field: {key}.")
        result[key] = value
    return result


def read_world_bathymetry(
    source: Path,
    *,
    checkpoint: Callable[[], None],
) -> tuple[WorldBathymetry, dict[str, object]]:
    from typing import cast

    checkpoint()
    root = source if source.is_dir() else source.parent
    manifest = root / "bathymetry.json" if source.is_dir() else source
    if root.is_symlink() or (root / "geography").is_symlink():
        raise ValueError("Bathymetry bundle directories cannot be links.")
    raw = _read(manifest, MAX_BATHYMETRY_MANIFEST_BYTES)
    try:
        value: object = json.loads(raw.decode("utf-8"), object_pairs_hook=_unique)
    except (UnicodeError, json.JSONDecodeError, RecursionError) as error:
        raise ValueError(f"Invalid bathymetry manifest: {error}") from error
    if not isinstance(value, dict):
        raise ValueError("Bathymetry manifest must be an object.")
    document = cast(dict[str, object], value)
    if (
        document.get("schema") != BATHYMETRY_SCHEMA
        or type(document.get("version")) is not int
        or document.get("version") != BATHYMETRY_VERSION
        or document.get("algorithm") != BATHYMETRY_ALGORITHM
    ):
        raise ValueError("Unsupported bathymetry format or algorithm.")
    outputs = document.get("outputs")
    if not isinstance(outputs, dict) or set(cast(dict[str, object], outputs)) != set(
        BATHYMETRY_OUTPUTS
    ):
        raise ValueError("Bathymetry outputs do not match the current contract.")
    records = cast(dict[str, object], outputs)
    captured: dict[str, bytes] = {}
    for name in BATHYMETRY_OUTPUTS:
        checkpoint()
        limit = (
            MAX_BATHYMETRY_INPUT_BYTES
            if name == "inputs.dmbathy.json"
            else 8 * 1024 * 1024
            if name == "bathymetry.npz"
            else 4 * 1024 * 1024
        )
        data = _read(root / name, limit)
        expected = {"sha256": sha256(data).hexdigest(), "bytes": len(data)}
        if canonical_json(records[name]) != canonical_json(expected):
            raise ValueError(f"Bathymetry output hash or length mismatch: {name}")
        captured[name] = data
    inputs = inputs_from_bytes(captured["inputs.dmbathy.json"])
    context, runtime = read_world_context(root / "geography", checkpoint=checkpoint)
    if (
        world_fingerprint(inputs.world) != world_fingerprint(context.world.project)
        or context.grid.shape[0] != inputs.settings.latitude_cells
        or not set(inputs.ocean_ids) <= {b.id for b in context.water_bodies}
    ):
        raise ValueError("Bathymetry inputs and geographic dependency disagree.")
    inputs = replace(inputs, world=context.world.project)
    specs = {
        "centre_water_body": (context.grid.shape, "<i4"),
        "bed_elevation_m": (context.grid.shape, "<f4"),
        "distance_depth_error_m": (context.grid.shape, "<f4"),
    }
    arrays = read_numeric_archive(captured["bathymetry.npz"], specs)
    checkpoint()
    centres = sample_water_centres(context.world, context.grid, checkpoint=checkpoint)
    if not np.array_equal(arrays["centre_water_body"], centres):
        raise ValueError("Bathymetry centre membership does not match retained water geometry.")
    bed, error = bathymetry_values(
        context.shore_distance_km,
        context.shore_sampling.max_error_km,
        np.isin(centres, inputs.ocean_ids),
        inputs.settings,
    )
    for key, expected_array in (("bed_elevation_m", bed), ("distance_depth_error_m", error)):
        if not np.array_equal(arrays[key], expected_array, equal_nan=True):
            raise ValueError(
                f"Bathymetry {key} does not match its retained scenario and geography."
            )
    result = WorldBathymetry(
        inputs,
        context,
        arrays["centre_water_body"],
        arrays["bed_elevation_m"],
        arrays["distance_depth_error_m"],
    )
    expected_document = bathymetry_document(result, runtime, records)
    if canonical_json(document) != canonical_json(expected_document):
        raise ValueError("Bathymetry manifest metadata or identity mismatch.")
    for name in BATHYMETRY_PREVIEWS:
        checkpoint()
        try:
            with Image.open(io.BytesIO(captured[name])) as preview:
                if preview.format != "PNG" or preview.size != context.grid.shape[::-1]:
                    raise ValueError("Bathymetry preview format or dimensions mismatch.")
                preview.verify()
        except (OSError, Image.DecompressionBombError) as error:
            raise ValueError(f"Invalid bathymetry preview: {name}") from error
    checkpoint()
    if _read(manifest, MAX_BATHYMETRY_MANIFEST_BYTES) != raw:
        raise ValueError("Bathymetry manifest changed while opening.")
    for name, data in captured.items():
        if file_sha256(root / name) != sha256(data).hexdigest():
            raise ValueError("Bathymetry output changed while opening.")
    return result, runtime
